language: go

go:
  - stable

before_install:
  - go get -t -v ./...
  - make npm-install

script:
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -F go -f "coverage.txt"
  - bash <(curl -s https://codecov.io/bash) -F javascript -f "coverage.lcov"
